// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace salesorder.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250110115506_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("COM_CUSTOMER", b =>
                {
                    b.Property<long>("COM_CUSTOMER_ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("COM_CUSTOMER_ID"));

                    b.Property<string>("CUSTOMER_NAME")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("COM_CUSTOMER_ID");

                    b.ToTable("Customers");
                });

            modelBuilder.Entity("sales_order.Models.SO_ITEM", b =>
                {
                    b.Property<long>("SO_ITEM_ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("SO_ITEM_ID"));

                    b.Property<string>("ITEM_NAME")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("PRICE")
                        .HasColumnType("float");

                    b.Property<int>("QUANTITY")
                        .HasColumnType("int");

                    b.Property<long>("SO_ORDER_ID")
                        .HasColumnType("bigint");

                    b.HasKey("SO_ITEM_ID");

                    b.HasIndex("SO_ORDER_ID");

                    b.ToTable("SoItems");
                });

            modelBuilder.Entity("sales_order.Models.SO_ORDER", b =>
                {
                    b.Property<long>("SO_ORDER_ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("SO_ORDER_ID"));

                    b.Property<string>("ADDRESS")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("COM_CUSTOMER_ID")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("ORDER_DATE")
                        .HasColumnType("datetime2");

                    b.Property<string>("ORDER_NO")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("SO_ORDER_ID");

                    b.HasIndex("COM_CUSTOMER_ID");

                    b.ToTable("SalesOrders");
                });

            modelBuilder.Entity("sales_order.Models.SO_ITEM", b =>
                {
                    b.HasOne("sales_order.Models.SO_ORDER", "SalesOrder")
                        .WithMany("SoItems")
                        .HasForeignKey("SO_ORDER_ID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SalesOrder");
                });

            modelBuilder.Entity("sales_order.Models.SO_ORDER", b =>
                {
                    b.HasOne("COM_CUSTOMER", "Customer")
                        .WithMany("SalesOrders")
                        .HasForeignKey("COM_CUSTOMER_ID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("COM_CUSTOMER", b =>
                {
                    b.Navigation("SalesOrders");
                });

            modelBuilder.Entity("sales_order.Models.SO_ORDER", b =>
                {
                    b.Navigation("SoItems");
                });
#pragma warning restore 612, 618
        }
    }
}
